### ISSUE TITLE
How to close or hide    TakePhoto

### ISSUE THREAD

**Issue by ihit** [anas10/AAImagePickerController#1]

**Comment by anas10** [comment]
What do you mean by close TakePhoto ?

**Comment by anas10** [comment]
What do you mean by close TakePhoto ?

**Comment by anas10** [comment]
I just added the possibility to hide the takePhoto (7b3ee0b62c2b1ddb28618a5488d848565e15c607).
You just have to set the showTakePhoto to false if you want to hide it.

I hope that's what you ask. If this is not the case, please give me more details.
