### ISSUE TITLE
Too many contexts. No space in contextList

### ISSUE THREAD

**Issue by KralMurat** [anas10/AAImagePickerController#2]
Hello,

I got this error below many times, searched on stackoverflow and It seems like a memory problem. I've found some solutions but couldnt find a way how to implement in library. Any help will be appriciated.

Thanks in advice

Fatal Exception: NSInternalInconsistencyException
Too many contexts. No space in contextList -[PLManagedObjectContext connectToChangeHub]

**Comment by anas10** [comment]
Hello,

could you please give me more informations about how you had this issue ?

Thanks
